import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import BackgroundLayout from './BackgroundLayout';
import { AuthProvider } from "@/components/AuthProvider";
import { TransparencyProvider } from "@/context/TransparencyContext";
import { ThemeProvider } from "@/context/ThemeContext";

// 使用系统字体替代Google Fonts，避免网络下载问题
const geistSans = {
  variable: "--font-geist-sans",
  className: "font-sans"
};

const geistMono = {
  variable: "--font-geist-mono",
  className: "font-mono"
};

export const metadata: Metadata = {
  title: "AI-SEC WEB",
  description: "Generated by mengxin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Dify AI 助手配置 - 暂时屏蔽 */}
        {/* <script
          dangerouslySetInnerHTML={{
            __html: `
              window.difyChatbotConfig = {
                token: 'Gc9fr2SqqNUvKS0X',
                baseUrl: 'http://192.168.50.195',
                inputs: {},
                systemVariables: {},
                userVariables: {}
              };
            `
          }}
        /> */}
        {/* Dify AI 助手样式 - 暂时屏蔽 */}
        {/* <style
          dangerouslySetInnerHTML={{
            __html: `
              #dify-chatbot-bubble-button {
                background-color: #1C64F2 !important;
              }
              #dify-chatbot-bubble-window {
                width: 24rem !important;
                height: 40rem !important;
              }
            `
          }}
        /> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-transparent`}
      >
        <AuthProvider>
          <ThemeProvider>
            <TransparencyProvider>
              <BackgroundLayout>{children}</BackgroundLayout>
            </TransparencyProvider>
          </ThemeProvider>
        </AuthProvider>
        {/* Dify AI 助手嵌入脚本 - 暂时屏蔽 */}
        {/* <Script
          src="http://192.168.50.195/embed.min.js"
          id="Gc9fr2SqqNUvKS0X"
          defer
        /> */}
      </body>
    </html>
  );
}
